import { ALERT_STATUS } from '../constants';

function makeAlert(rule, transaction, index) {
  return {
    id: `${rule.id}-${transaction.transactionId}-${index}`,
    alertId: `SIM-${rule.id}-${transaction.transactionId}`,
    ruleId: rule.id,
    ruleName: rule.ruleName,
    ruleType: rule.ruleType,
    transactionId: transaction.transactionId,
    accountId: transaction.accountId,
    severity: rule.severity || 'MEDIUM',
    status: ALERT_STATUS.OPEN,
    reason: buildReason(rule, transaction),
    createdAt: transaction.transactionTime,
    updatedAt: transaction.transactionTime,
    history: [
      {
        status: ALERT_STATUS.OPEN,
        changedAt: transaction.transactionTime,
        note: 'Alert generated by simulated frontend engine'
      }
    ]
  };
}

function buildReason(rule, transaction) {
  switch (rule.ruleType) {
    case 'AMOUNT_THRESHOLD':
      return `Amount ${transaction.amount} crossed threshold ${rule.threshold}`;
    case 'NEW_PAYEE':
      return `Potential new payee for account ${transaction.accountId}`;
    case 'DAILY_LIMIT':
      return `Daily amount may exceed limit ${rule.threshold}`;
    case 'VELOCITY':
      return `Velocity window of ${rule.timeWindowMinutes || 0} minutes may be exceeded`;
    default:
      return 'Rule condition matched';
  }
}

export function deriveAlertsFromData(transactions, rules) {
  if (!Array.isArray(transactions) || !Array.isArray(rules)) {
    return [];
  }

  const activeRules = rules.filter((rule) => rule.active);
  const alerts = [];

  activeRules.forEach((rule) => {
    if (rule.ruleType === 'AMOUNT_THRESHOLD') {
      transactions.forEach((tx, index) => {
        if (Number(tx.amount) > Number(rule.threshold || 0)) {
          alerts.push(makeAlert(rule, tx, index));
        }
      });
    }
  });

  return alerts.sort((a, b) => new Date(b.createdAt) - new Date(a.createdAt));
}

export function canTransitionAlert(currentStatus, targetStatus) {
  const transitions = {
    [ALERT_STATUS.OPEN]: [ALERT_STATUS.ACKNOWLEDGED],
    [ALERT_STATUS.ACKNOWLEDGED]: [ALERT_STATUS.INVESTIGATING, ALERT_STATUS.DISMISSED],
    [ALERT_STATUS.INVESTIGATING]: [ALERT_STATUS.CLOSED, ALERT_STATUS.DISMISSED],
    [ALERT_STATUS.CLOSED]: [],
    [ALERT_STATUS.DISMISSED]: []
  };

  return transitions[currentStatus]?.includes(targetStatus) || false;
}

